default: &default
  <<: *default

  # listeners credentials
  sheets_token: <%= ENV['GOOGLE_SHEETS_TOKEN'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
